# Generated by Django 3.2.15 on 2023-11-04 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='gsagood',
            name='manufacturer',
            field=models.CharField(default='', max_length=255, verbose_name='Manufacturer'),
        ),
    ]
