# Generated by Django 3.2.15 on 2023-11-01 01:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ingramgood',
            name='sku',
        ),
        migrations.RemoveField(
            model_name='synnexgood',
            name='sku',
        ),
        migrations.RemoveField(
            model_name='synnexgood',
            name='td_snx',
        ),
        migrations.AlterField(
            model_name='gsagood',
            name='source',
            field=models.IntegerField(default=0, verbose_name='source'),
        ),
    ]
