# Generated by Django 3.2.15 on 2023-11-05 01:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0002_gsagood_manufacturer'),
    ]

    operations = [
        migrations.AddField(
            model_name='gsagood',
            name='description_1',
            field=models.CharField(default='', max_length=2047, verbose_name='Product Description'),
        ),
        migrations.AddField(
            model_name='gsagood',
            name='description_2',
            field=models.CharField(default='', max_length=2047, verbose_name='Description Provided by XXX'),
        ),
    ]
