# Generated by Django 3.2.15 on 2023-11-05 20:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0003_auto_20231105_0120'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gsagood',
            name='description',
        ),
        migrations.AddField(
            model_name='gsagood',
            name='mfr_part_no',
            field=models.CharField(default='', max_length=255, verbose_name='MfrPartNo'),
        ),
    ]
